### PR TITLE
Updates to Readme and Example.csv Int32BE

### PR DESCRIPTION
**Pull request by RichardBH**
Updates to Readme and Example.csv Int32BE.
Spelling mistakes, elaboration and clarification on references.

### CODE REVIEW

**Comment by mbs38** [comment]
Nice! Thank you.

**Comment by RichardBH** [comment]
I am thinking of adding a deadband and scaling functions.
But I'm not sure how to do this in the CSV though...

What do you think of this:
For each reference which is a register, at the end we put optional
functions:
# type, topic, reference, rw, *multiplyfactor, addfactor,deadband*
e.g.:

poll,kitchen,7,0,12,holding_register,0.5
ref,someWritableRegister,0,rw,0.1,0,1.0

This would then multiply by 0.1 and add 0, and only send an MQTT if the
scaled value changes by 1.0

How can we make this optional to retain backwards compatibility?

Cheers, Rich.

**Comment by mbs38** [comment]
Sounds like a great idea.

Regarding a backwards compatible implementation I don't see any problems:
In the part where we are reading the config file we could do something like 

deadband = None
try:
    deadband = row["col6"]
except:
    pass
currentPoller.addReference(Reference(row["topic"],reference,"",row["col3"],multiplier, addend, deadband, currentPoller)

and then of course change addReference( ... ), the reference Class etc. accordingly.

What do you think?
Max

**Comment by RichardBH** [comment]
Yes, that could work.

BTW. I am using this code to pull data from a Factory PLC and then push it
as MQTT through to a Broker then into an InfluxDB database via Telegraf. So
far it is working well.
The MQTT will eventually be sent to the cloud for cloud sync as well.

The other thing I would like to do, when  get around to it, is to be able
to break out a int16 register into bits with each bit having its own MQTT
topic and value.
I currently have a need for this on a weigh scale.
Might need a different datatype, with the reference number in the reference
being the bit number to pull out. The Poller could poll multiple registers,
so long as there is a reference for each bit. E.g. if it polls two
registers would need 32 references one for each bit.

This looks tricky to do as it may require the relative references to be
calculated a different way for this case.
What do you think?

Regards,
Richard.

**Comment by mbs38** [comment]
Nice setup. Haven't tried InfluxDB but I certainly will.

Well how about this:

poll,kitchen,7,0,12,holding_register,0.5
ref,bit0ofRegister0,0:0,r
ref,bit1ofRegister0,0:1,r
ref,bit2ofRegister0,0:2,r 
ref,contentOfRegister2,2,rw

this would ensure backwards compatibility and we do not need to change anything about the polling part..

**Pull request merged**
