### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RichardBH**
Added configuration examples.

### CODE REVIEW

**Comment by RichardBH** [comment]
Ok, Item 4 done. Its not perfect, but its a start. Havent tested it on Serial comms, Will probably get to that in a week or two, but have tested it thoroughly on MODBUS TCP and MQTT. Serial uses the same error handling as TCP in the PyModbus library so it should work the same.

Not sure about the --Verbosity level, maybe there is a better way to do this, but its easy to use it when you just see the connection strings, at level 2, but if you want full debugging info on the modbus and MQTT read/writes that is useful at level 3. Perhaps, rather than verbosity levels, We should just have default to connections and errors only, with a --Silent option and a --Debug option?

**Review by mbs38 — COMMENTED** [review]
Hi,
nice work. Thx for cleaning up the mess a bit. I have completely forgotten that I actually had 'blah' as a help statement :-)

One thing: verbosity level 3 is not useful in my opinion because it produces way too many prints for the polls. I am polling something in the realm of 10+ devices with 30 pollers in total at the highest speed possible (--set-loop-break 0 and all pollers that do timing critical stuff set to 0 wait time). On the other hand I am only writing stuff to the devices every couple of seconds - if I need to debug that it will be hard to actually find the prints for writing...

I suggest we introduce another level so sth like. 0=silent, 1=erros only, 2=connections 3=when writing to devices 4=all

Just fix that and I will merge. 
Thanks!
Max

edit: and we should make verbosity=2 the default. A new user will probably have errors in the config und should get a decent chance of finding them.

**Comment by RichardBH** [comment]
Sounds good.
The Paho library doesn't give any feedback when it loses a connection until
about a minute in when the on_disconnect function is called, I am not sure
if it is saving the published messages during that minute, I don't think it
is. I need to dig a bit deeper into the Paho Library, but its not too
important at this stage...

Richard.

**Comment by bikeymouse** [comment]
Hi, I am polling 2 devices and have set the Verbosity level at 1. In general all works fine.
The thing is, that I have multiple times per day that there is a "connection problem". 

In itself that is probably not so bad (this seems normal for Modbus?) as it resolves itself, however on every connection error it produces about 200 error messages with multiple succes/error status changes, _within a second_.
E..g.:
2020-02-04T15:42:30.279009524Z Error talking to slave device:1, trying again...
2020-02-04T15:42:30.279032753Z MODBUS connected successfully
2020-02-04T15:42:30.279056034Z Error talking to slave device:2, trying again...
2020-02-04T15:42:30.279081190Z Error talking to slave device:2, trying again...
2020-02-04T15:42:30.279104836Z Error talking to slave device:2, trying again...
2020-02-04T15:42:30.279128221Z Error talking to slave device:2, trying again...
2020-02-04T15:42:30.279151398Z Error talking to slave device:1, trying again...
2020-02-04T15:42:30.279174627Z MODBUS connected successfully
2020-02-04T15:42:30.279199210Z Error talking to slave device:2, trying again...
2020-02-04T15:42:30.279222543Z Error talking to slave device:2, trying again...
2020-02-04T15:42:30.279245929Z Error talking to slave device:2, trying again...
etc. times 200

Is that "as designed" or just happening at my situation? And/or could this be made more resilient, e.g. holding off to try to reconnect within 1 second? 

To put this into perspective: I'm trying to read about 10 values from 2 (Eastron SDM630) meters, once every 60 seconds.

**Comment by mbs38** [comment]
That is a rather interesting issue...

I will look into it. Can you post your csv file and command line arguments please?

Best,
Max

**Comment by bikeymouse** [comment]
Great that you want to look at it.
I'm using Docker with environment variables, but my command line comes down to:

modbus2mqtt.py --rtu /dev/ttyUSB-RS485 --rtu-baud 9600 rtu-parity none --set-modbus-timeout 1 mqtt-host localhost --config config.csv verbosity 1

This is what is in my csv file:
```
"type","topic","col2","col3","col4","col5","col6"

poll,Charger,1,52,2,input_register,60.0
ref,TotalSystemPower,52,r,float32LE

poll,Charger,1,72,2,input_register,60.0
ref,TotalEnergyImport,72,r,float32LE

poll,Charger,1,0,18,input_register,60.0
ref,VoltagePhase1,0,r,float32LE
ref,VoltagePhase2,2,r,float32LE
ref,VoltagePhase3,4,r,float32LE
ref,CurrentPhase1,6,r,float32LE
ref,CurrentPhase2,8,r,float32LE
ref,CurrentPhase3,10,r,float32LE
ref,ActivePowerPhase1,12,r,float32LE
ref,ActivePowerPhase2,14,r,float32LE
ref,ActivePowerPhase3,16,r,float32LE

poll,Solar,2,52,2,input_register,60.0
ref,TotalSystemPower,52,r,float32LE

poll,Solar,2,72,2,input_register,60.0
ref,TotalEnergyImport,72,r,float32LE

poll,Solar,2,0,18,input_register,60.0
ref,VoltagePhase1,0,r,float32LE
ref,VoltagePhase2,2,r,float32LE
ref,VoltagePhase3,4,r,float32LE
ref,CurrentPhase1,6,r,float32LE
ref,CurrentPhase2,8,r,float32LE
ref,CurrentPhase3,10,r,float32LE
ref,ActivePowerPhase1,12,r,float32LE
ref,ActivePowerPhase2,14,r,float32LE
ref,ActivePowerPhase3,16,r,float32LE
```

**Comment by mbs38** [comment]
Hi bikeymouse,

unfortunately I cannot reproduce the issue on my system. However, I have found some issues concerning the handling of connection losses in serial mode. These things need to be fixed which might resolve your issue on the way. Also, I think I have found a bug in pymodbus...

I will provide you with a new version for testing.

By the way:
> I have multiple times per day that there is a "connection problem".
> 
> In itself that is probably not so bad (this seems normal for Modbus?)

That is not normal for Modbus. A correctly wired RS485 network produces zero errors. Usually the issues you want to look for are things like missing ground connections (cheap Chinese gear often has no gnd connection), ground loops, missing termination, too much termination, breaks in one of the wires and missing or bad biasing network.

Best,
Max

**Comment by bikeymouse** [comment]
> That is not normal for Modbus. A correctly wired RS485 network produces zero errors. Usually the issues you want to look for are things like missing ground connections (cheap Chinese gear often has no gnd connection), ground loops, missing termination, too much termination, breaks in one of the wires and missing or bad biasing network.

Ok, then I will have to look at my set-up again, although I don't know what I still can improve.

I'm using shielded twisted pair cable of 2 meters, connecting to 2 Eastron SDM630 meters, with a 120 Ohm terminating resistor at the meter at the end of the cable and an other 120 Ohm resistor at the RS-485 gateway. I have connected the shield of the cable to ground and connected the shield to all the ground terminals of the 2 SDM's and the RS-485 gateway. 

At first I used an USB RS-485 adaptor, but now have changed to an [Waveshare RS485 to Ethernet gateway.](https://www.waveshare.com/rs232-485-to-eth.htm) to see if that would help, but that is not the case.

The only thing I still can think of is that I would need to have pull-up and pull-down on resp. the "-" and "+" lines, but I would expect that this is also done by the SDM630 or the RS485 gateway. Do you think that would help? I have to say that if I use a multimeter I don't measure +5V on either of the A or B lines, is that an indication?

The only other thing I can think of is that one of my SDM630's is "somewhat faulty" as it has 10x the amount of errors as the other one, possibly also disturbing the communication.

**Pull request merged**
